### PR TITLE
Release v1.0.3

### PR DESCRIPTION
**Pull request by davidrapin**
- upload built assets to github

### CODE REVIEW

**Comment by enys** [comment]
@davidrapin the expected way is to trigger a release via Jenkins.

**Comment by enys** [comment]
This would allow full generation of the description of this Pr.

**Comment by davidrapin** [comment]
@enys I always try to find release triggers in jenkins, and simply never find them.
Where should I search?

**Comment by enys** [comment]
Either you search for what you want to release, and select the one that contains release in the name, or you go to the  'lke release' folder

**Pull request closed without merging**
